# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Data models for the AMC allocator environment."""

from __future__ import annotations

import math
from typing import Dict, List

from openenv.core.env_server.types import Action, Observation, State
from pydantic import Field, field_validator


class PortfolioAction(Action):
    """Desired portfolio weights for the next rebalance."""

    target_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Target asset weights. Cash is implied by any unallocated weight.",
    )
    reason: str | None = Field(
        default=None,
        description="Optional explanation for the rebalance decision.",
    )

    @field_validator("target_weights")
    @classmethod
    def validate_target_weights(cls, value: Dict[str, float]) -> Dict[str, float]:
        cleaned: Dict[str, float] = {}
        for asset, weight in value.items():
            if not asset or not asset.strip():
                raise ValueError("asset names must be non-empty")
            if not math.isfinite(weight):
                raise ValueError(f"weight for {asset!r} must be finite")
            cleaned[asset.strip().upper()] = float(weight)
        return cleaned


class AllocatorObservation(Observation):
    """Environment observation for one allocator decision step."""

    task_id: str = Field(..., description="Active task identifier.")
    task_description: str = Field(..., description="Human-readable task summary.")
    step_index: int = Field(..., ge=0, description="Current decision step index.")
    steps_remaining: int = Field(..., ge=0, description="Remaining decisions in the episode.")
    prices: Dict[str, float] = Field(..., description="Current asset prices.")
    signals: Dict[str, float] = Field(
        ...,
        description="Precomputed predictive signals in the range [-1.0, 1.0].",
    )
    current_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Current invested asset weights before the next action.",
    )
    cash_weight: float = Field(..., ge=0.0, le=1.0, description="Current cash allocation.")
    portfolio_value: float = Field(..., ge=0.0, description="Current portfolio NAV.")
    turnover: float = Field(..., ge=0.0, description="Turnover generated by the last rebalance.")
    risk_metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Task-specific risk and market summary metrics.",
    )


class AllocatorState(State):
    """Extended environment state exposed through the OpenEnv state endpoint."""

    task_id: str = Field(default="signal_following", description="Active task identifier.")
    task_description: str = Field(default="", description="Human-readable task summary.")
    total_steps: int = Field(default=0, ge=0, description="Total decisions in the episode.")
    current_step: int = Field(default=0, ge=0, description="Current completed step count.")
    assets: List[str] = Field(default_factory=list, description="Tradable asset universe.")
    holdings: Dict[str, float] = Field(
        default_factory=dict,
        description="Current position sizes in asset units.",
    )
    current_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Current invested asset weights.",
    )
    cash_weight: float = Field(default=1.0, ge=0.0, le=1.0, description="Current cash weight.")
    portfolio_value: float = Field(default=1.0, ge=0.0, description="Current portfolio NAV.")
    nav_history: List[float] = Field(default_factory=list, description="Episode NAV history.")
    turnover_history: List[float] = Field(
        default_factory=list,
        description="Per-step turnover values.",
    )
    reward_history: List[float] = Field(
        default_factory=list,
        description="Per-step shaped rewards.",
    )
    portfolio_return_history: List[float] = Field(
        default_factory=list,
        description="Per-step realized portfolio returns before costs.",
    )
    signal_alignment_history: List[float] = Field(
        default_factory=list,
        description="Per-step alignment between allocated weights and signals.",
    )
    risk_metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Latest risk summary emitted in the observation.",
    )
    last_turnover: float = Field(default=0.0, ge=0.0, description="Latest turnover.")
    last_reward: float = Field(default=0.0, description="Latest shaped reward.")
    last_action_reason: str | None = Field(
        default=None,
        description="Optional latest action rationale.",
    )
