# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Data models for the Round 2 committee environment."""

from __future__ import annotations

import math
from typing import Dict, List, Literal

from openenv.core.env_server.types import Action, Observation, State
from pydantic import Field, field_validator


ActionType = Literal[
    "query_research",
    "query_risk",
    "allocate",
    "revise_allocation",
    "hold",
    "move_to_cash",
]


class PortfolioAction(Action):
    """Committee-style action emitted by the Portfolio Manager."""

    action_type: ActionType = Field(
        default="hold",
        description="Type of committee action to take this step.",
    )
    allocation_template: str | None = Field(
        default=None,
        description="Optional discrete allocation template name.",
    )
    query_target: str | None = Field(
        default=None,
        description="Optional research focus such as an asset ticker or SECTOR.",
    )
    target_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Optional custom asset weights. Cash is implied by any unallocated weight.",
    )
    reason: str | None = Field(
        default=None,
        description="Optional explanation for the committee decision.",
    )

    @field_validator("target_weights")
    @classmethod
    def validate_target_weights(cls, value: Dict[str, float]) -> Dict[str, float]:
        cleaned: Dict[str, float] = {}
        for asset, weight in value.items():
            if not asset or not asset.strip():
                raise ValueError("asset names must be non-empty")
            if not math.isfinite(weight):
                raise ValueError(f"weight for {asset!r} must be finite")
            cleaned[asset.strip().upper()] = float(weight)
        return cleaned

    @field_validator("query_target")
    @classmethod
    def normalize_query_target(cls, value: str | None) -> str | None:
        if value is None:
            return None
        normalized = value.strip().upper()
        return normalized or None

    @field_validator("allocation_template")
    @classmethod
    def normalize_allocation_template(cls, value: str | None) -> str | None:
        if value is None:
            return None
        normalized = value.strip().lower()
        return normalized or None


class AllocatorObservation(Observation):
    """Observation visible to the trainable Portfolio Manager."""

    task_id: str = Field(..., description="Active task identifier.")
    task_description: str = Field(..., description="Human-readable task summary.")
    step_index: int = Field(..., ge=0, description="Current decision step index.")
    steps_remaining: int = Field(..., ge=0, description="Remaining decisions in the episode.")
    prices: Dict[str, float] = Field(..., description="Current asset prices.")
    signals: Dict[str, float] = Field(
        ...,
        description="Current market signals in the range [-1.0, 1.0].",
    )
    current_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Current invested asset weights before the next action.",
    )
    cash_weight: float = Field(..., ge=0.0, le=1.0, description="Current cash allocation.")
    portfolio_value: float = Field(..., ge=0.0, description="Current portfolio NAV.")
    turnover: float = Field(..., ge=0.0, description="Turnover generated by the last action.")
    risk_metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Latest market and risk summary metrics.",
    )
    active_constraints: Dict[str, float] = Field(
        default_factory=dict,
        description="Current mandate and risk constraints.",
    )
    reward_components: Dict[str, float] = Field(
        default_factory=dict,
        description="Last step reward component breakdown.",
    )
    research_notes: List[str] = Field(
        default_factory=list,
        description="Recent research notes available to the PM.",
    )
    risk_notes: List[str] = Field(
        default_factory=list,
        description="Recent risk notes available to the PM.",
    )
    available_allocation_templates: Dict[str, str] = Field(
        default_factory=dict,
        description="Discrete allocation templates exposed by the environment.",
    )
    outstanding_risk_alert: bool = Field(
        default=False,
        description="Whether the PM is currently under elevated risk pressure.",
    )
    queries_remaining: int = Field(
        default=0,
        ge=0,
        description="Remaining advisory queries in the episode.",
    )


class AllocatorState(State):
    """Extended environment state exposed through the OpenEnv state endpoint."""

    task_id: str = Field(default="guided_allocation", description="Active task identifier.")
    task_description: str = Field(default="", description="Human-readable task summary.")
    total_steps: int = Field(default=0, ge=0, description="Total decisions in the episode.")
    current_step: int = Field(default=0, ge=0, description="Current completed step count.")
    assets: List[str] = Field(default_factory=list, description="Tradable asset universe.")
    holdings: Dict[str, float] = Field(
        default_factory=dict,
        description="Current position sizes in asset units.",
    )
    current_weights: Dict[str, float] = Field(
        default_factory=dict,
        description="Current invested asset weights.",
    )
    cash_weight: float = Field(default=1.0, ge=0.0, le=1.0, description="Current cash weight.")
    portfolio_value: float = Field(default=1.0, ge=0.0, description="Current portfolio NAV.")
    nav_history: List[float] = Field(default_factory=list, description="Episode NAV history.")
    turnover_history: List[float] = Field(
        default_factory=list,
        description="Per-step turnover values.",
    )
    reward_history: List[float] = Field(
        default_factory=list,
        description="Per-step shaped rewards.",
    )
    portfolio_return_history: List[float] = Field(
        default_factory=list,
        description="Per-step realized portfolio returns before costs.",
    )
    signal_alignment_history: List[float] = Field(
        default_factory=list,
        description="Per-step alignment between allocated weights and market signals.",
    )
    information_usage_history: List[float] = Field(
        default_factory=list,
        description="Per-step usage score for analyst information.",
    )
    risk_response_history: List[float] = Field(
        default_factory=list,
        description="Per-step response quality to risk pressure.",
    )
    compliance_penalty_history: List[float] = Field(
        default_factory=list,
        description="Per-step compliance penalty values.",
    )
    reward_component_history: List[Dict[str, float]] = Field(
        default_factory=list,
        description="Reward breakdown history.",
    )
    risk_metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Latest risk summary emitted in the observation.",
    )
    active_constraints: Dict[str, float] = Field(
        default_factory=dict,
        description="Current risk and mandate constraints.",
    )
    research_notes_history: List[str] = Field(
        default_factory=list,
        description="Research commentary visible to the PM.",
    )
    risk_notes_history: List[str] = Field(
        default_factory=list,
        description="Risk commentary visible to the PM.",
    )
    action_history: List[str] = Field(
        default_factory=list,
        description="Portfolio Manager action history.",
    )
    allocation_template_history: List[str] = Field(
        default_factory=list,
        description="Chosen allocation templates over time.",
    )
    hidden_regime_history: List[str] = Field(
        default_factory=list,
        description="Internal regime labels used by the environment.",
    )
    latest_research_view: Dict[str, float] = Field(
        default_factory=dict,
        description="Latest noisy research score snapshot.",
    )
    latest_risk_view: Dict[str, float] = Field(
        default_factory=dict,
        description="Latest risk guidance snapshot.",
    )
    query_count: int = Field(default=0, ge=0, description="Number of advisory queries used.")
    outstanding_risk_alert: bool = Field(
        default=False,
        description="Whether the PM currently faces elevated risk pressure.",
    )
    compliance_violations: int = Field(
        default=0,
        ge=0,
        description="Count of compliance or mandate breaches.",
    )
    last_turnover: float = Field(default=0.0, ge=0.0, description="Latest turnover.")
    last_reward: float = Field(default=0.0, description="Latest shaped reward.")
    last_action_type: str = Field(default="reset", description="Latest action type.")
    last_action_reason: str | None = Field(
        default=None,
        description="Optional latest action rationale.",
    )
